### ISSUE TITLE
Pipeline quebra ao tentar importar proposições apensadas

### ISSUE THREAD

**Issue by danielhmarinho** [parlametria/leggo-backend#379]
Traceback (most recent call last):
File "./manage.py", line 15, in
execute_from_command_line(sys.argv)
File "/usr/local/lib/python3.7/site-packages/django/core/management/init.py", line 419, in execute_from_command_line
utility.execute()
File "/usr/local/lib/python3.7/site-packages/django/core/management/init.py", line 413, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 354, in run_from_argv
self.execute(*args, **cmd_options)
File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 398, in execute
output = self.handle(*args, **options)
File "/agora-digital-backend/api/management/commands/import_all_data.py", line 9, in handle
import_all_data()
File "/agora-digital-backend/api/management/commands/import_utils.py", line 1211, in import_all_data
import_proposicoes_apensadas()
File "/agora-digital-backend/api/management/commands/import_utils.py", line 1142, in import_proposicoes_apensadas
id_leggo_original_df = grouped.get_group(group_index)[
File "/usr/local/lib/python3.7/site-packages/pandas/core/groupby/groupby.py", line 877, in get_group
raise KeyError(name)
KeyError: ('179e36e222adcdda45793ad2793ca830', nan)

**Comment by ArthurJahn** [comment]
Estamos testando a correção do pipeline em ambiente de homologação pra validar a solução.
